## Formação Cientista de dados - Prof. Fernando Amaral

Variáveis e Objetos

In [1]:
#Cria variável do tipo inteiro
x = 1
print(x)
#Cria variável do tipo float
y = 3.13
print(y)
#Cria variável do tipo string
m = "Python"
m = 'Python'
print(m)
#Cria variável do tipo lógica
w = True  
y = False
print(y)

#calculadora
x = 10
y = 20
z = 100
w = (x + y) * z / 100
print(w)

#exibir texto no console
print("Este texto será impresso no console")
print(x)
print("Texto e duas variáveis: ", x ,", ", z)

#verificar tipo
print(type(x))
print(type(m))


1
3.13
Python
False
30.0
Este texto será impresso no console
10
Texto e duas variáveis:  10 ,  100
<class 'int'>
<class 'str'>


In [3]:
#entrada de dados
print("Informe o valor: ")
i = input()
#mostra tipo string
print(type(i))

#entrada de valor com msg separada e junto
print("Informe o valor: ")
i = input()
# ou
i = input("Informe o valor: ")

#conversão de valores
#para inteiro
var = input("Informe o valor: ")
print(type(var))
var = int(var)
print(type(var))

#para float
var = input("Informe o valor: ")
print(type(var))
var = float(var)
print(type(var))

Informe o valor: 
4
<class 'str'>
Informe o valor: 
r
Informe o valor: 52
Informe o valor: 4
<class 'str'>
<class 'int'>
Informe o valor: 9
<class 'str'>
<class 'float'>


Estrutura de Decisão

In [4]:
nota = 7
if nota >= 7:
    print("Aprovado")
    print("Parabéns!")
else:
    print("Reprovado")
    
#só mudar o valor da variável
nota = 5
if nota >= 7:
    print("Aprovado")
else:
    print("Reprovado")
    
#Testar com 4,5 e 7
nota = 7
if nota <= 4:
    print("Reprovado")
elif nota > 4 and nota <=6:
    print("Exame")
else:
    print("Aprovado")

Aprovado
Parabéns!
Reprovado
Aprovado


Estrutura de Repetição

In [5]:
#exemplo com while
count = 1
while count <= 5:
    print(count)
    count += 1
    
#range(0, 10, 1):
#range(inicio, parada, incremento)
#o python "igonora" o ultimo valor de intervalos
#O incremento pode ser negativo

#for normal
for n in range(0, 10):
    print(n+1)
    
for n in range(1, 11):
    print(n)
    
    
#for decrecente
for n in range(10, 0,-1):
    print(n)
    
#exemplo com break
#vai parar no 3 pois o break está antes do print
for n in range(0, 10):
    if n==4:
        break
    print(n)
    
#exemplo com continue
#vai pular o numero 4
for n in range(0, 10):
    if n==4:
        continue
    print(n)

1
2
3
4
5
1
2
3
4
5
6
7
8
9
10
1
2
3
4
5
6
7
8
9
10
10
9
8
7
6
5
4
3
2
1
0
1
2
3
0
1
2
3
5
6
7
8
9


Estruturas de Dados - Listas/Tuplas/Dicionarios/Conjuntos

In [6]:
#formas de criar listas
lst = [1,2,3,4,5]
print(lst)

#vários tipos
lst2 = [1,2,3,"4",True]
print(lst2)

#lista com lista
lst3 = [12,[1,2,3,4,5],"a"]
print(lst3)

#criando lista com range
lst4 = list(range(0,10))
print(lst4)

#comprimento da lista
print(len(lst))

#acessando elemento
print(lst[0])
#posiçõo 1 é uma lista
print(lst3[1])
#alterando posição
lst[0] = 4
print(lst)

#percorrendo lista
for n in range(0, len(lst4)):
    print(lst4[n]+1)

[1, 2, 3, 4, 5]
[1, 2, 3, '4', True]
[12, [1, 2, 3, 4, 5], 'a']
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
5
1
[1, 2, 3, 4, 5]
[4, 2, 3, 4, 5]
1
2
3
4
5
6
7
8
9
10


In [7]:
#dicionários: estrutura chave/valor
Notas = {'João': 6.0, 'Maria': 8.0, 'Pedro': 6.5}
print(Notas)

print(Notas['João'])

#Todasd as chaves
Notas.keys()

#todos os valores
Notas.values()

#Testa logicamente a existência
print('João' in Notas)
print('Fernando' in Notas)

#apaga um elemento
del Notas['João']
print(Notas)

#inclui um elemento
Notas['Ana'] = 9
print(Notas)

#busca um valor, se não encontrar mostra segundo parametro
Notas.get('Geraldo',"Não encontrado!")

#sets são conjuntos não ordenados de elementos não repetidos
bigdata = {'Spark', 'Hive', "Sqoop"}
print(bigdata)

#verifica existência
print('Spark' in bigdata)

#adiciona elemento
bigdata.add('Hadoop')
bigdata

#número de elementos
print(len(bigdata))

bigdata.add("Spark")
bigdata

#tuplas são listas que não podem ser alteradas
#listas usam [], tuplas usam ()
tupla = (1,2,3,4,5,6,7)
tupla

tupla[4]

#dicionários em que cada posição recebe uma tupla
dic2 = {(0, 1): 0, (1, 2): 1, (2, 3): 2, (3, 4): 3, (4, 5): 4,(5, 6): 5, (6, 7): 6, (7, 8): 7, (8, 9): 8, (9, 10): 9}
dic2

print(type(Notas))
print(type(bigdata))
print(type(tupla))

{'João': 6.0, 'Maria': 8.0, 'Pedro': 6.5}
6.0
True
False
{'Maria': 8.0, 'Pedro': 6.5}
{'Maria': 8.0, 'Pedro': 6.5, 'Ana': 9}
{'Spark', 'Hive', 'Sqoop'}
True
4
<class 'dict'>
<class 'set'>
<class 'tuple'>


Funções e Funções Padrão

In [8]:
def imprime():
    print("esta é uma função")

imprime()

#com parametro
def imprime(n):
    print(n)

imprime("Impressão deste texto")

#com retorno
def potencia(n):
    return n * n

x = potencia(3)
print(x)

#com valor default
def intervalo(inic=1,fim=10):
    for n in range(inic, fim+1):
        print(n)

x = intervalo(1,10)
y = intervalo()

esta é uma função
Impressão deste texto
9
1
2
3
4
5
6
7
8
9
10
1
2
3
4
5
6
7
8
9
10


In [9]:
#funções internas
print(abs(-200))
lst = [1,2,30,30,45]
print("Maior valor: ", max(lst))
print("Menor valor: ", min(lst))
print("Soma: ", sum(lst))
print("Arredondamento: ", round(2.34567,2))

#statistica
from statistics import *
print("Média: ", mean(lst))
print("Mediana: ", median(lst))
print("Moda: ", mode(lst))

#desvio padrão da amostra
print("Desvio padrão: ", stdev(lst))

#variancia da amostra
print("Variância: ", variance(lst))

from numpy import *
a = random.random((8,8))
print(type(a))
print(a)

200
Maior valor:  45
Menor valor:  1
Soma:  108
Arredondamento:  2.35
Média:  21.6
Mediana:  30
Moda:  30
Desvio padrão:  19.346834366376324
Variância:  374.3
<class 'numpy.ndarray'>
[[0.41961119 0.98608584 0.58952468 0.44168508 0.46429839 0.56804106
  0.75161042 0.34030625]
 [0.40884998 0.04283604 0.45257618 0.50787289 0.41902582 0.27468449
  0.93180051 0.31577997]
 [0.28959274 0.03276955 0.68526925 0.28419895 0.66152465 0.67518977
  0.38622299 0.6706352 ]
 [0.20262296 0.91797778 0.83859978 0.18827714 0.36499921 0.12229975
  0.07223353 0.00448819]
 [0.38644402 0.0187856  0.38538678 0.66716452 0.97517412 0.99968302
  0.41567722 0.41917822]
 [0.34646236 0.34706273 0.31482117 0.50724825 0.06077563 0.38771105
  0.46629059 0.14851943]
 [0.64096656 0.17777765 0.92736856 0.46776819 0.06252213 0.08736807
  0.10637232 0.25536297]
 [0.84290184 0.99299181 0.96715077 0.91848689 0.30050595 0.57680982
  0.12992954 0.91990473]]


Numpy - Usado para operações matematicas e dados multidimencionais 

Tipos de dados

In [2]:
import numpy as np  # Importando o numpy
boolean = np.bool_(True)  # Criando uma classe boleana
print(boolean, type(boolean))  # Imprimindo seu tipo

texto = np.string_('Este e um texto') # Informando que o tipo é texto, porem ele é do tipo byte caracteres do tipo ascii sendo eles 8 bits
print(texto, type(texto))  # Imprimindo seu tipo

texto = np.unicode_('Este é um texto') # Informando que agora o tipo é unicode que se asemelha ao tipo str
print(texto, type(texto))  # Imprimindo seu tipo

True <class 'numpy.bool_'>
b'Este e um texto' <class 'numpy.bytes_'>
Este é um texto <class 'numpy.str_'>


In [3]:
inteiro = np.intc(-102)  # Valor inteiro que ocupa 32 bits e pode ser negativo (receber o sinal -)
uinteiro = np.uintc(102) # Valor inteiro que ocupa 32 bits nao pode ser negativo (sem sinal)
long = np.int_(102120102)  # Valor inteiro que ocupa 64 bits e pode ser negativo (receber o sinal -)
ulong = np.uint(102) # Valor inteiro que ocupa 64 bits nao pode ser negativo (sem sinal)

print(inteiro, type(inteiro))
print(uinteiro, type(uinteiro))
print(long, type(long))
print(ulong, type(ulong))

ponto_flutuante = np.float_(12051.84) # Valor 64 bits
ponto_flutuante2 = np.float32(12051.84) # Valor 32 bits

print(ponto_flutuante, type(ponto_flutuante))
print(ponto_flutuante2, type(ponto_flutuante2))

-102 <class 'numpy.intc'>
102 <class 'numpy.uintc'>
102120102 <class 'numpy.int32'>
102 <class 'numpy.uint32'>
12051.84 <class 'numpy.float64'>
12051.84 <class 'numpy.float32'>


In [5]:
# Outras formas de declarar tipos
array = np.array([1,2,3,4,5,6,7,8,9,0]) # Criando um array
print(array) 
print(type(array))
print(array.dtype)

# Alterando os valores do array
array = np.array([1,2,3,4,5,6,7,8,9,0], dtype= np.int8) # Passando tipo do dados
print(array) 
print(type(array))
print(array.dtype)

[1 2 3 4 5 6 7 8 9 0]
<class 'numpy.ndarray'>
int32
[1 2 3 4 5 6 7 8 9 0]
<class 'numpy.ndarray'>
int8


In [7]:
# Usando POO para criar novos tipos
class Pessoa:
    def __init__(self, nome, idade):
        self.nome = nome
        self.idade = idade

        
        
array = np.array([Pessoa("Wendell", 30), Pessoa('Lidia', 31)])
print(array)
print(type(array))
print(array.dtype, end='\n\n')

print(array[0].nome, array[1].idade)

<class 'numpy.ndarray'>
object

Wendell 31


Propriedades de Arrays

In [8]:
array = np.array([1,2,3,4,5,6,7,8,9,0])
print(array)  # Array
print(array.ndim)  # Numeros de dimensões do array
print(array.size)  # Tamanho do array
print(len(array))  # Quantidade de indices do array
print(array.shape)  # Tamanho de linhas do array
print(array.dtype)  # tipo de dados do array
print(array.itemsize)  # tamanho de bits do array
print(array.nbytes)  # Numeros de bytes do array

[1 2 3 4 5 6 7 8 9 0]
1
10
10
(10,)
int32
4
40


In [9]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)  # Array
print(array.ndim)  # Numeros de dimensões do array
print(array.size)  # Tamanho do array
print(len(array))  # Quantidade de indices do array
print(array.shape)  # Tamanho de linhas do array
print(array.dtype)  # tipo de dados do array
print(array.itemsize)  # tamanho de bits do array
print(array.nbytes)  # Numeros de bytes do array

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
9
3
(3, 3)
int32
4
36


In [14]:
array1 = np.zeros(9)  # Vetor com valores 0
array2 = np.ones(1)  # Vetor com valores 1
array3 = np.empty(6)  # Matriz com valores aleatorios
array4 = np.identity(4)  # Matriz com valores 0 e 1 os valores 1 ficam na diagonal
matriz1 = np.zeros((3,3))  # Matriz de bidimencional
matriz2 = np.ones((4,4))  # Matriz de bidimencional
array5 = np.arange(2,17,2)  # O arange segue o mesmo principio do range
matriz3 = np.full((4,4), 10)  # Gerando uma matriz 
matriz4 = np.random.rand(4,4) # Matrix de numeros float
matriz5 = np.random.randint(2,10, (5,5))  # Matriz de numero inteiros

print(array1, end='\n\n')
print(array2, end='\n\n')
print(array3, end='\n\n')
print(array4, end='\n\n')
print(array5, end='\n\n')
print(matriz1, end='\n\n')
print(matriz2, end='\n\n')
print(matriz3, end='\n\n')
print(matriz4, end='\n\n')
print(matriz5, end='\n\n')

[0. 0. 0. 0. 0. 0. 0. 0. 0.]

[1.]

[0. 0. 0. 0. 0. 0.]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[ 2  4  6  8 10 12 14 16]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]

[[0.75164565 0.88925592 0.27020037 0.97267122]
 [0.20509657 0.24412629 0.91427992 0.19703946]
 [0.45635804 0.0692884  0.77794511 0.04588342]
 [0.18368324 0.07889923 0.22035472 0.05843358]]

[[8 8 6 7 2]
 [9 9 3 3 5]
 [8 7 5 4 9]
 [4 9 8 7 2]
 [8 5 2 4 8]]



List Comprehension

In [15]:
# Criando uma matriz com list comprehension
matriz = np.array([[x for x in range(0,3)],
                  [x for x in range(3,6)],
                  [x for x in range(6,9)]])
print(matriz)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Slicing

In [18]:
# Retornando valores com slice *Reforçando o que ja estudei
array = np.array([[1,2,3,4,5,6,7,8,9],
                  [10,11,12,13,14,15,16,17,18],
                  [19,20,21,22,23,24,25,26,27]])

print(array, end='\n\n')
print(array[1,::2]) # Retornando do indice 1 todos os valores com o step sendo 2
print(array[:,2]) # Retornando todos os valores da coluna 2
# [linhas : colunas] para retornar os valores seja linha ou coluna é somente trabalhar a partir dos pontos


[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]]

[10 12 14 16 18]
[ 3 12 21]
