## Formação Cientista de dados - Prof. Fernando Amaral

Variáveis e Objetos

In [1]:
#Cria variável do tipo inteiro
x = 1
print(x)
#Cria variável do tipo float
y = 3.13
print(y)
#Cria variável do tipo string
m = "Python"
m = 'Python'
print(m)
#Cria variável do tipo lógica
w = True  
y = False
print(y)

#calculadora
x = 10
y = 20
z = 100
w = (x + y) * z / 100
print(w)

#exibir texto no console
print("Este texto será impresso no console")
print(x)
print("Texto e duas variáveis: ", x ,", ", z)

#verificar tipo
print(type(x))
print(type(m))


1
3.13
Python
False
30.0
Este texto será impresso no console
10
Texto e duas variáveis:  10 ,  100
<class 'int'>
<class 'str'>


In [2]:
#entrada de dados
print("Informe o valor: ")
i = input()
#mostra tipo string
print(type(i))

#entrada de valor com msg separada e junto
print("Informe o valor: ")
i = input()
# ou
i = input("Informe o valor: ")

#conversão de valores
#para inteiro
var = input("Informe o valor: ")
print(type(var))
var = int(var)
print(type(var))

#para float
var = input("Informe o valor: ")
print(type(var))
var = float(var)
print(type(var))

Informe o valor: 
45
<class 'str'>
Informe o valor: 
58
Informe o valor: 54
Informe o valor: 21
<class 'str'>
<class 'int'>
Informe o valor: 49
<class 'str'>
<class 'float'>


Estrutura de Decisão

In [3]:
nota = 7
if nota >= 7:
    print("Aprovado")
    print("Parabéns!")
else:
    print("Reprovado")
    
#só mudar o valor da variável
nota = 5
if nota >= 7:
    print("Aprovado")
else:
    print("Reprovado")
    
#Testar com 4,5 e 7
nota = 7
if nota <= 4:
    print("Reprovado")
elif nota > 4 and nota <=6:
    print("Exame")
else:
    print("Aprovado")

Aprovado
Parabéns!
Reprovado
Aprovado


Estrutura de Repetição

In [4]:
#exemplo com while
count = 1
while count <= 5:
    print(count)
    count += 1
    
#range(0, 10, 1):
#range(inicio, parada, incremento)
#o python "igonora" o ultimo valor de intervalos
#O incremento pode ser negativo

#for normal
for n in range(0, 10):
    print(n+1)
    
for n in range(1, 11):
    print(n)
    
    
#for decrecente
for n in range(10, 0,-1):
    print(n)
    
#exemplo com break
#vai parar no 3 pois o break está antes do print
for n in range(0, 10):
    if n==4:
        break
    print(n)
    
#exemplo com continue
#vai pular o numero 4
for n in range(0, 10):
    if n==4:
        continue
    print(n)

1
2
3
4
5
1
2
3
4
5
6
7
8
9
10
1
2
3
4
5
6
7
8
9
10
10
9
8
7
6
5
4
3
2
1
0
1
2
3
0
1
2
3
5
6
7
8
9


Estruturas de Dados - Listas/Tuplas/Dicionarios/Conjuntos

In [5]:
#formas de criar listas
lst = [1,2,3,4,5]
print(lst)

#vários tipos
lst2 = [1,2,3,"4",True]
print(lst2)

#lista com lista
lst3 = [12,[1,2,3,4,5],"a"]
print(lst3)

#criando lista com range
lst4 = list(range(0,10))
print(lst4)

#comprimento da lista
print(len(lst))

#acessando elemento
print(lst[0])
#posiçõo 1 é uma lista
print(lst3[1])
#alterando posição
lst[0] = 4
print(lst)

#percorrendo lista
for n in range(0, len(lst4)):
    print(lst4[n]+1)

[1, 2, 3, 4, 5]
[1, 2, 3, '4', True]
[12, [1, 2, 3, 4, 5], 'a']
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
5
1
[1, 2, 3, 4, 5]
[4, 2, 3, 4, 5]
1
2
3
4
5
6
7
8
9
10


In [6]:
#dicionários: estrutura chave/valor
Notas = {'João': 6.0, 'Maria': 8.0, 'Pedro': 6.5}
print(Notas)

print(Notas['João'])

#Todasd as chaves
Notas.keys()

#todos os valores
Notas.values()

#Testa logicamente a existência
print('João' in Notas)
print('Fernando' in Notas)

#apaga um elemento
del Notas['João']
print(Notas)

#inclui um elemento
Notas['Ana'] = 9
print(Notas)

#busca um valor, se não encontrar mostra segundo parametro
Notas.get('Geraldo',"Não encontrado!")

#sets são conjuntos não ordenados de elementos não repetidos
bigdata = {'Spark', 'Hive', "Sqoop"}
print(bigdata)

#verifica existência
print('Spark' in bigdata)

#adiciona elemento
bigdata.add('Hadoop')
bigdata

#número de elementos
print(len(bigdata))

bigdata.add("Spark")
bigdata

#tuplas são listas que não podem ser alteradas
#listas usam [], tuplas usam ()
tupla = (1,2,3,4,5,6,7)
tupla

tupla[4]

#dicionários em que cada posição recebe uma tupla
dic2 = {(0, 1): 0, (1, 2): 1, (2, 3): 2, (3, 4): 3, (4, 5): 4,(5, 6): 5, (6, 7): 6, (7, 8): 7, (8, 9): 8, (9, 10): 9}
dic2

print(type(Notas))
print(type(bigdata))
print(type(tupla))

{'João': 6.0, 'Maria': 8.0, 'Pedro': 6.5}
6.0
True
False
{'Maria': 8.0, 'Pedro': 6.5}
{'Maria': 8.0, 'Pedro': 6.5, 'Ana': 9}
{'Hive', 'Spark', 'Sqoop'}
True
4
<class 'dict'>
<class 'set'>
<class 'tuple'>


Funções e Funções Padrão

In [7]:
def imprime():
    print("esta é uma função")

imprime()

#com parametro
def imprime(n):
    print(n)

imprime("Impressão deste texto")

#com retorno
def potencia(n):
    return n * n

x = potencia(3)
print(x)

#com valor default
def intervalo(inic=1,fim=10):
    for n in range(inic, fim+1):
        print(n)

x = intervalo(1,10)
y = intervalo()

esta é uma função
Impressão deste texto
9
1
2
3
4
5
6
7
8
9
10
1
2
3
4
5
6
7
8
9
10


In [8]:
#funções internas
print(abs(-200))
lst = [1,2,30,30,45]
print("Maior valor: ", max(lst))
print("Menor valor: ", min(lst))
print("Soma: ", sum(lst))
print("Arredondamento: ", round(2.34567,2))

#statistica
from statistics import *
print("Média: ", mean(lst))
print("Mediana: ", median(lst))
print("Moda: ", mode(lst))

#desvio padrão da amostra
print("Desvio padrão: ", stdev(lst))

#variancia da amostra
print("Variância: ", variance(lst))

from numpy import *
a = random.random((8,8))
print(type(a))
print(a)

200
Maior valor:  45
Menor valor:  1
Soma:  108
Arredondamento:  2.35
Média:  21.6
Mediana:  30
Moda:  30
Desvio padrão:  19.346834366376324
Variância:  374.3
<class 'numpy.ndarray'>
[[0.26753534 0.8088493  0.51178154 0.05015808 0.15973235 0.1056769
  0.57640348 0.09724776]
 [0.58379801 0.23608091 0.42217509 0.68116636 0.01525028 0.3552819
  0.80795657 0.80832246]
 [0.51816531 0.27760362 0.93284834 0.41291015 0.68963568 0.01259781
  0.89896167 0.21738018]
 [0.21199623 0.28633126 0.19239872 0.61716776 0.28293075 0.56366958
  0.21269468 0.60934443]
 [0.80140323 0.916318   0.09181295 0.79475172 0.66984638 0.27235735
  0.45912278 0.70068013]
 [0.71334803 0.42936104 0.60431325 0.8115246  0.76947947 0.68229687
  0.29671856 0.85020799]
 [0.67289872 0.45399324 0.46352499 0.90721416 0.63955013 0.73627744
  0.05209694 0.50525411]
 [0.72880896 0.92191046 0.57300255 0.09833804 0.8507201  0.44533961
  0.34554833 0.42460386]]


Numpy - Usado para operações matematicas e dados multidimencionais 

Tipos de dados

In [15]:
import numpy as np  # Importando o numpy
boolean = np.bool_(True)  # Criando uma classe boleana
print(boolean, type(boolean))  # Imprimindo seu tipo

texto = np.string_('Este e um texto') # Informando que o tipo é texto, porem ele é do tipo byte caracteres do tipo ascii sendo eles 8 bits
print(texto, type(texto))  # Imprimindo seu tipo

texto = np.unicode_('Este é um texto') # Informando que agora o tipo é unicode que se asemelha ao tipo str
print(texto, type(texto))  # Imprimindo seu tipo

True <class 'numpy.bool_'>
b'Este e um texto' <class 'numpy.bytes_'>
Este é um texto <class 'numpy.str_'>


In [10]:
inteiro = np.intc(-102)  # Valor inteiro que ocupa 32 bits e pode ser negativo (receber o sinal -)
uinteiro = np.uintc(102) # Valor inteiro que ocupa 32 bits nao pode ser negativo (sem sinal)
long = np.int_(102120102)  # Valor inteiro que ocupa 64 bits e pode ser negativo (receber o sinal -)
ulong = np.uint(102) # Valor inteiro que ocupa 64 bits nao pode ser negativo (sem sinal)

print(inteiro, type(inteiro))
print(uinteiro, type(uinteiro))
print(long, type(long))
print(ulong, type(ulong))

ponto_flutuante = np.float_(12051.84) # Valor 64 bits
ponto_flutuante2 = np.float32(12051.84) # Valor 32 bits

print(ponto_flutuante, type(ponto_flutuante))
print(ponto_flutuante2, type(ponto_flutuante2))

-102 <class 'numpy.intc'>
102 <class 'numpy.uintc'>
102120102 <class 'numpy.int32'>
102 <class 'numpy.uint32'>
12051.84 <class 'numpy.float64'>
12051.84 <class 'numpy.float32'>


In [11]:
# Outras formas de declarar tipos
array = np.array([1,2,3,4,5,6,7,8,9,0]) # Criando um array
print(array) 
print(type(array))
print(array.dtype)

# Alterando os valores do array
array = np.array([1,2,3,4,5,6,7,8,9,0], dtype= np.int8) # Passando tipo do dados
print(array) 
print(type(array))
print(array.dtype)

[1 2 3 4 5 6 7 8 9 0]
<class 'numpy.ndarray'>
int32
[1 2 3 4 5 6 7 8 9 0]
<class 'numpy.ndarray'>
int8


In [12]:
# Usando POO para criar novos tipos
class Pessoa:
    def __init__(self, nome, idade):
        self.nome = nome
        self.idade = idade

        
        
array = np.array([Pessoa("Wendell", 30), Pessoa('Lidia', 31)])
print(array)
print(type(array))
print(array.dtype, end='\n\n')

print(array[0].nome, array[1].idade)

<class 'numpy.ndarray'>
object

Wendell 31


Propriedades de Arrays

In [13]:
array = np.array([1,2,3,4,5,6,7,8,9,0])
print(array)  # Array
print(array.ndim)  # Numeros de dimensões do array
print(array.size)  # Tamanho do array
print(len(array))  # Quantidade de indices do array
print(array.shape)  # Tamanho de linhas do array
print(array.dtype)  # tipo de dados do array
print(array.itemsize)  # tamanho de bits do array
print(array.nbytes)  # Numeros de bytes do array

[1 2 3 4 5 6 7 8 9 0]
1
10
10
(10,)
int32
4
40


In [14]:
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)  # Array
print(array.ndim)  # Numeros de dimensões do array
print(array.size)  # Tamanho do array
print(len(array))  # Quantidade de indices do array
print(array.shape)  # Tamanho de linhas do array
print(array.dtype)  # tipo de dados do array
print(array.itemsize)  # tamanho de bits do array
print(array.nbytes)  # Numeros de bytes do array

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
9
3
(3, 3)
int32
4
36


In [15]:
array1 = np.zeros(9)  # Vetor com valores 0
array2 = np.ones(1)  # Vetor com valores 1
array3 = np.empty(6)  # Matriz com valores aleatorios
array4 = np.identity(4)  # Matriz com valores 0 e 1 os valores 1 ficam na diagonal
matriz1 = np.zeros((3,3))  # Matriz de bidimencional
matriz2 = np.ones((4,4))  # Matriz de bidimencional
array5 = np.arange(2,17,2)  # O arange segue o mesmo principio do range
matriz3 = np.full((4,4), 10)  # Gerando uma matriz 
matriz4 = np.random.rand(4,4) # Matrix de numeros float
matriz5 = np.random.randint(2,10, (5,5))  # Matriz de numero inteiros

print(array1, end='\n\n')
print(array2, end='\n\n')
print(array3, end='\n\n')
print(array4, end='\n\n')
print(array5, end='\n\n')
print(matriz1, end='\n\n')
print(matriz2, end='\n\n')
print(matriz3, end='\n\n')
print(matriz4, end='\n\n')
print(matriz5, end='\n\n')

[0. 0. 0. 0. 0. 0. 0. 0. 0.]

[1.]

[0. 0. 0. 0. 0. 0.]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

[ 2  4  6  8 10 12 14 16]

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]

[[10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]
 [10 10 10 10]]

[[0.9078404  0.11602931 0.54664641 0.5069077 ]
 [0.30265609 0.38321877 0.13060181 0.87156223]
 [0.80602623 0.03310689 0.95073977 0.81109073]
 [0.46424642 0.8059194  0.46920103 0.20131815]]

[[2 3 9 3 5]
 [6 5 9 9 3]
 [9 8 3 2 8]
 [4 8 8 2 9]
 [2 4 4 7 3]]



List Comprehension

In [16]:
# Criando uma matriz com list comprehension
matriz = np.array([[x for x in range(0,3)],
                  [x for x in range(3,6)],
                  [x for x in range(6,9)]])
print(matriz)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


Slicing

In [17]:
# Retornando valores com slice *Reforçando o que ja estudei
array = np.array([[1,2,3,4,5,6,7,8,9],
                  [10,11,12,13,14,15,16,17,18],
                  [19,20,21,22,23,24,25,26,27]])

print(array, end='\n\n')
print(array[1,::2]) # Retornando do indice 1 todos os valores com o step sendo 2
print(array[:,2]) # Retornando todos os valores da coluna 2
# [linhas : colunas] para retornar os valores seja linha ou coluna é somente trabalhar a partir dos pontos


[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]]

[10 12 14 16 18]
[ 3 12 21]


In [22]:
# Iterando arrays
vetor = np.array([9,4,8,6,3])
for i in vetor:
    print(i)

matriz = np.array([[9,4,8,6,3],[1,2,3,4,5]])
for i in matriz:
    for j in i:
        print(j)
        
matriz = np.array([[9,4,8,6,3],[1,2,3,4,5]])
print(matriz)

# Usando uma função para percorre por coluna
for x in np.nditer(matriz, order='F'):
    print(x)

9
4
8
6
3
9
4
8
6
3
1
2
3
4
5
[[9 4 8 6 3]
 [1 2 3 4 5]]
9
1
4
2
8
3
6
4
3
5


Alterando Dimensões

In [11]:
import numpy as np
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)

# Usando a função reshape para alterar a dimensão
array = array.reshape(9)
print(array)  # Transformando uma matriz em um vetor

# Transformando dimensões com reshape
array2 = np.array([i for i in range(0,27)])
print(array2)
array2 = array2.reshape(3,9)
print(array2)
array2 = array2.reshape(3,3,3)
print(array2)

# Usando a função flatten() para retornar em um vetor 
array2 = array2.flatten()
array2

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]
[[ 0  1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16 17]
 [18 19 20 21 22 23 24 25 26]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [13]:
# Operações matematicas entre os arrays
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])

print(array1 + array2)
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)
print(array1 ** array2)
print(array1 // array2)

# Broadcast 
array1 = np.array([1,2,3])
array2 = np.array([[4,5,6],[5,2,1]])

print(array1 + array2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[  1  32 729]
[0 0 0]
[[5 7 9]
 [6 4 4]]


In [18]:
# Usando a função concatenate para concatenação
array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
array12 = np.concatenate((array1,array2), axis=0)
print(array12)

# Concatenando por linhas 
array1 = np.array([[1,2,3],[7,8,9]])
array2 = np.array([[4,5,6],[10,11,12]])
array12 = np.concatenate((array1,array2), axis=0)
print(array12)

# Concatenando por colunas
array12 = np.concatenate((array1,array2), axis=1)
print(array12)

array1 = np.array([1,2,3])
array2 = np.array([4,5,6])
array12v = np.vstack((array1,array2))
array12h = np.hstack((array1,array2))
print(array12v)
print(array12h)

[1 2 3 4 5 6]
[[ 1  2  3]
 [ 7  8  9]
 [ 4  5  6]
 [10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [22]:
# Divisão de array com o metodo split
array = np.array([1,2,3,4,5,6])
print(np.split(array,2))
print(np.split(array,3))

[array([1, 2, 3]), array([4, 5, 6])]
[array([1, 2]), array([3, 4]), array([5, 6])]


In [25]:
# Filtrando elementos com where
array_find = np.where(array >= 4)
print(array_find)

array = np.array([1,-1,-3,0,6,3,-78])
array_find = np.where( (array > 0) & (array <= 10) )
print(array_find)

# Usando a função filter para retornar o valor da condição
array = np.array([1,0,1,1,0,0,0,1,1,0])
filter = array == 1
filter_array = array[filter]
print(filter_array)

(array([4], dtype=int64),)
(array([0, 4, 5], dtype=int64),)
[1 1 1 1 1]


In [27]:
# Ordenação
array = np.array([2,5,4,1,3,96,8,9,6,2,3])
print(np.sort(array, kind='quicksort'))

[ 1  2  2  3  3  4  5  6  8  9 96]


In [38]:
# Operações Aritméticas com funções
arr1 = np.array([[2,4,1,3,96,8,9],[8,1,9,6,4,8,9]])
arr2 = np.array([[1,3,8,9,6,2,3],[9,4,5,6,2,1,3]])

print(np.add(arr1, arr2))  # Soma
print(np.subtract(arr1, arr2))  # Subtração
print(np.multiply(arr1, arr2))  # Multiplicação
print(np.divide(arr1, arr2))  # Divisão
print(np.power(arr1, arr2))  # Ponteciação
print(np.floor_divide(arr1, arr2))  # Divisão inteiro
print(np.divmod(arr1, arr2))  # Resto da divisão
print(np.sqrt(arr1))  # Raiz quadrada
print(np.around(arr1,2))  # Arredondar com 2 casas decimais
print(np.floor(arr1,2))  # Arredondar para cima
print(np.ceil(arr1,2))  # Arredondar para cima

[[  3   7   9  12 102  10  12]
 [ 17   5  14  12   6   9  12]]
[[ 1  1 -7 -6 90  6  6]
 [-1 -3  4  0  2  7  6]]
[[  2  12   8  27 576  16  27]
 [ 72   4  45  36   8   8  27]]
[[ 2.          1.33333333  0.125       0.33333333 16.          4.
   3.        ]
 [ 0.88888889  0.25        1.8         1.          2.          8.
   3.        ]]
[[         2         64          1      19683 1073741824         64
         729]
 [ 134217728          1      59049      46656         16          8
         729]]
[[ 2  1  0  0 16  4  3]
 [ 0  0  1  1  2  8  3]]
(array([[ 2,  1,  0,  0, 16,  4,  3],
       [ 0,  0,  1,  1,  2,  8,  3]]), array([[0, 1, 1, 3, 0, 0, 0],
       [8, 1, 4, 0, 0, 0, 0]]))
[[1.41421356 2.         1.         1.73205081 9.79795897 2.82842712
  3.        ]
 [2.82842712 1.         3.         2.44948974 2.         2.82842712
  3.        ]]
[[ 2  4  1  3 96  8  9]
 [ 8  1  9  6  4  8  9]]


In [45]:
# Acumuladores
print(np.sum(arr1))  # Soma acumulada de todos os valores
print(np.sum(arr1, axis=1))  # Soma acumulada de todos os valores por coluna
print(np.cumsum(arr1))  # Soma acumulada por valores
print(np.cumprod(arr1))  # Multiplicação acumulada por valores
print(np.min(arr1))  # Menor valor
print(np.max(arr1))  # Maior valor
print(np.abs(arr1))  # Valor absoluto positivo

168
[123  45]
[  2   6   7  10 106 114 123 131 132 141 147 151 159 168]
[          2           8           8          24        2304       18432
      165888     1327104     1327104    11943936    71663616   286654464
 -2001731584  -835715072]
1
96
[[ 2  4  1  3 96  8  9]
 [ 8  1  9  6  4  8  9]]


In [105]:
# Respostas dos exercicios do modulo
ex1 = np.array(range(0,10))
print(ex1)
ex2 = np.array([i for i in range(0,10)])
print(ex2)
ex3 = np.array(range(0,9))
print(ex3.reshape(3,3))
ex6 = np.array([[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20]])
print(ex6[0][0],ex6[1][-1])
ex7 = np.random.randint(5,20, (3,3))
print(ex7)
ex8 = np.random.randint(1,50, (3,3))
print(sum(ex8))
ex9 = np.array([i for i in range(0,100,2)])
print(ex9)
ex10 = np.random.randint(1,100, (4,9))
print(ex10.reshape(6,6))

def ex11(ar1,ar2,ar3):
    array_conc = np.concatenate((ar1,ar2,ar3), axis=0)
    return array_conc

ar1 = np.array([np.random.randint(20, size=10)])
ar2 = np.array([np.random.randint(30, size=10)])
ar3 = np.array([np.random.randint(40, size=10)])
ex11(ar1, ar2, ar3)

ex12 = np.array([6,-4,9,3,-2,-7])
print(np.abs(ex12))

ex13 = np.array([6,-8,9,-3,3,8,9])
def pos_ex13(arr):
    return len(np.where(arr > 0)[0])
print(pos_ex13(ex13))

def ex15(arr):
    return np.any(arr)
print(ex15(ex13))

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
1 20
[[18 10  8]
 [15 18 10]
 [ 8  6  5]]
[ 27 100  70]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46
 48 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78 80 82 84 86 88 90 92 94
 96 98]
[[41 61 86 99 29 54]
 [82 16 21 97 60 45]
 [79 63 91 44 90 98]
 [57 88 92 23 10  1]
 [20 99 86  3 67 61]
 [56 45 51 26 71  3]]
[6 4 9 3 2 7]
5
True


Pandas - é uma biblioteca criada para a linguagem Python para manipulação e análise de dados. 

In [7]:
# Importando o pandas
import pandas as pd

# Criando uma Serie com os dados, tipo do dado, nome do df e o nome de cada indice
minha_serie = pd.Series([1,2,3,4,5], dtype='i4', name='Meus dados', index=['Um', 'Dois', 'Três', 'Quatro', 'Cinco'])
minha_serie

Um        1
Dois      2
Três      3
Quatro    4
Cinco     5
Name: Meus dados, dtype: int32

In [14]:
# Criando DataFrame
nomes = ['Roger','Lucas','Cristiano','Maria']
df = pd.DataFrame(nomes)
df

0
0      Roger
1      Lucas
2  Cristiano
3      Maria

In [30]:
num = {'Nome':['Miguel','Arthur','Théo','Heitor','Gael','Davi','Bernardo','Gabriel','Ravi','Noah'],
       'Idade':[54, 72, 75, 66, 57, 70, 37, 60, 54, 61],
       'A':[196, 250, 303, 225, 44, 19, 35, 235, 484, 174],
       'B':[349, 200, 131, 202, 198, 157, 404, 355, 162, 12],
       'C':[73, 433, 468, 151, 297, 102, 496, 196, 485, 442],
       'D':[148, 209, 243, 59, 361, 435, 108, 320, 47, 447]}

df = pd.DataFrame(num)
df

Nome  Idade    A    B    C    D
0    Miguel     54  196  349   73  148
1    Arthur     72  250  200  433  209
2      Théo     75  303  131  468  243
3    Heitor     66  225  202  151   59
4      Gael     57   44  198  297  361
5      Davi     70   19  157  102  435
6  Bernardo     37   35  404  496  108
7   Gabriel     60  235  355  196  320
8      Ravi     54  484  162  485   47
9      Noah     61  174   12  442  447

In [31]:
# Carregando dados 
data = pd.read_csv('./dados/pessoas.csv')
data

Nome  Idade     Profissão  Altura
0      Roger     45     Arquiteto    1.80
1  Cristiano     34   Programador    1.73
2      Diego     56        Médico    1.78
3   Jeferson     71    Aposentado    1.77
4       José     46  Desempregado    1.71
5      Maria     31    Enfermeira    1.69

In [37]:
# Localizando valores dentro do dataframe
data.loc[data['Nome'] == 'Roger']

Nome  Idade  Profissão  Altura
0  Roger     45  Arquiteto     1.8

In [39]:
# Retornando quantidade de colunas e linhas
len(data.columns), len(data.index)

(4, 6)

In [40]:
# Retornando as colunas
data.columns

Index(['Nome', 'Idade', 'Profissão', 'Altura'], dtype='object')

In [41]:
# Verificando o tamanho do dataframe
data.shape

(6, 4)

In [42]:
# Percorrendo cada linha pela coluna
for indice, linha in data.iterrows():
    print(indice, linha[0], linha[1], linha[2])

0 Roger 45 Arquiteto
1 Cristiano 34 Programador
2 Diego 56 Médico
3 Jeferson 71 Aposentado
4 José 46 Desempregado
5 Maria 31 Enfermeira


In [63]:
# Acessando valore Individuais e Slicing
display(data.loc[data.Nome == 'Roger',['Idade']]) # loc retorna pelo nome do indice
display(data.iloc[0]['Idade']) # iloc retorna pelo indice
display(data.iloc[0][0])

Idade
0     45

45

'Roger'

In [90]:
# Retornando com Slicing
data.loc[1:3] # Retornando pelo valor no indice
data.iloc[1:4] # Retornando pelo indice

# Acessando valor da coluna pelo indice
idade = data['Idade']
idade[2] # Usando slicing
idade.loc[data['Nome'] == 'Cristiano'] # Retornando a partir de uma condição

# Retornando vetores com mais de uma coluna
data[['Idade', 'Altura']]

Idade  Altura
0     45    1.80
1     34    1.73
2     56    1.78
3     71    1.77
4     46    1.71
5     31    1.69

In [89]:
# Slicing de colunas
data.iloc[:,1:3]
data.loc[:,'Idade':'Profissão']

Idade     Profissão
0     45     Arquiteto
1     34   Programador
2     56        Médico
3     71    Aposentado
4     46  Desempregado
5     31    Enfermeira

In [88]:
# Gerando mascara no dataframe
mask = data['Idade'] < 50  # passando a condição logica 
novo_df = data[mask]  # adicionamos a variavel com a mascara no novo df
novo_df

# nova mascara
novo_dframe = [(data['Idade'] > 40) & (data['Altura'] > 1.75)]
novo_dframe = data[mask]
novo_dframe

Nome  Idade     Profissão  Altura
0      Roger     45     Arquiteto    1.80
1  Cristiano     34   Programador    1.73
4       José     46  Desempregado    1.71
5      Maria     31    Enfermeira    1.69